/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddWorkbookItem: typeof import('./src/components/dataset/AddWorkbookItem.vue')['default']
    DataOriginItem: typeof import('./src/components/dataorigin/DataOriginItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkbookItem: typeof import('./src/components/dataset/WorkbookItem.vue')['default']
  }
}
